name:                peregrine
version:             0.1.0.0
github:              "alexmccord/peregrine"
license:             Apache-2.0
author:              "Alexander McCord"
maintainer:          "alex@mccord.dev"
copyright:           "2024 Alexander McCord"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexmccord/peregrine#readme>

default-extensions:
- ApplicativeDo
- OverloadedRecordDot
- OverloadedStrings
- OverloadedLists
- RecordWildCards
- FlexibleContexts
- FlexibleInstances
- DeriveAnyClass
- GADTs
- DataKinds
- KindSignatures
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators
- PatternSynonyms
- ViewPatterns
- BinaryLiterals

dependencies:
- base >=4.7 && <5
- containers >=0.6.7 && <0.7
- transformers >=0.6.1.0 && <0.7
- mtl >=2.3.1 && <3
- bytestring >=0.11.5.3 && <0.12
- bv-sized >=1.0.5 && <2

ghc-options:
- -Wall
- -Widentities
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - megaparsec >=9.5.0 && <10

executables:
  peregrine-exe:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - peregrine
    - optparse-applicative >=0.18.1.0 && <1

tests:
  peregrine-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - peregrine
    - hspec >=2.11.9 && <3
    - optparse-applicative >=0.18.1.0 && <1
