name:                clu
version:             0.1.0.0
github:              "alexmccord/clu"
license:             Apache-2.0
author:              "Alexander McCord"
maintainer:          "alex@mccord.dev"
copyright:           "2024 Alexander McCord"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexmccord/clu#readme>

default-extensions:
- OverloadedStrings
- OverloadedRecordDot
- RecordWildCards
- ApplicativeDo
- GeneralizedNewtypeDeriving

dependencies:
- base >=4.7 && <5
- containers >=0.6.7 && <0.7
- transformers >=0.6.1.0 && <0.7
- mtl >=2.3.1 && <3

ghc-options:
- -Wall
- -Widentities
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - megaparsec >=9.5.0 && <10

executables:
  clu-exe:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clu
    - optparse-applicative >=0.18.1.0 && <1

tests:
  clu-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clu
    - hspec >=2.11.9 && <3
