name:                clu
version:             0.1.0.0
github:              "alexmccord/clu"
license:             Apache-2.0
author:              "Alexander McCord"
maintainer:          "alex@mccord.dev"
copyright:           "2024 Alexander McCord"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexmccord/clu#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Widentities
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  clu-exe:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clu

tests:
  clu-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clu
