[package]
name = "eyrie"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
peregrine = { path = "../peregrine" }
serde = { version = "1.0.217", features = ["serde_derive"] }
thiserror = "2.0.11"
toml = "0.8.19"
git2 = "0.20.0"
